apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environment-appset
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: todo-3tier
spec:
  generators:
    - list:
        elements:
          - environment: staging
            branch: main
            path: k3s/backend
            namespace: todo-3tier-staging
          - environment: staging-frontend
            branch: main
            path: k3s/frontend
            namespace: todo-3tier-staging
  template:
    metadata:
      name: 'todo-{{environment}}'
      labels:
        app.kubernetes.io/part-of: todo-3tier
        managed-by: argocd-applicationset
    spec:
      project: todo-3tier
      source:
        repoURL: https://github.com/lekhana-vemuri/To-Do-k3s.git
        targetRevision: '{{branch}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true
      revisionHistoryLimit: 3
