apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres
  namespace: todo-3tier

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
      - name: postgres

        image: postgres:16-alpine

        imagePullPolicy: Always

        ports:
        - containerPort: 5432

        envFrom:
        - secretRef:
            name: todo-secret

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "300m"
            memory: "256Mi"