apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo-frontend
  namespace: todo-3tier

spec:
  replicas: 1
  revisionHistoryLimit: 1

  selector:
    matchLabels:
      app: todo-frontend

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  template:
    metadata:
      labels:
        app: todo-frontend

    spec:
      containers:
      - name: todo-frontend

        image: lekhanavemuri/todo-frontend:7

        imagePullPolicy: Always

        ports:
        - containerPort: 80

        envFrom:
        - secretRef:
            name: todo-secret

        startupProbe:
          tcpSocket:
            port: 80
          failureThreshold: 30
          periodSeconds: 5

        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 15

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "300m"
            memory: "256Mi"