apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo-frontend
  namespace: todo-3tier

spec:
  replicas: 2
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: todo-frontend

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  template:
    metadata:
      labels:
        app: todo-frontend
        app.kubernetes.io/name: todo-frontend
        app.kubernetes.io/part-of: todo-3tier

      annotations:
        test: "frontend-verification-v2"

    spec:
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: todo-frontend
                topologyKey: kubernetes.io/hostname

      containers:
      - name: todo-frontend

        image: lekhanavemuri/todo-frontend:12

        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 80

        envFrom:
        - secretRef:
            name: todo-secret

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL

        startupProbe:
          tcpSocket:
            port: 80
          failureThreshold: 30
          periodSeconds: 5

        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 15

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "300m"
            memory: "256Mi"