apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: todo-backend-secret
  namespace: todo-3tier

spec:
  refreshInterval: 1m

  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  target:
    name: todo-backend-secret

  data:
    - secretKey: DB_HOST
      remoteRef:
        key: todo-backend
        property: DB_HOST

    - secretKey: DB_PORT
      remoteRef:
        key: todo-backend
        property: DB_PORT

    - secretKey: BACKEND_PORT
      remoteRef:
        key: todo-backend
        property: BACKEND_PORT