apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
data:
  DB_HOST: "10.20.10.38"
  DB_PORT: "5432"
  POSTGRES_HOST: "10.20.10.38"
  PORT: "4000"
  BACKEND_PORT: "4000"
  REACT_APP_API_URL: "http://10.20.10.38:3000"
