apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo-backend
  namespace: todo-3tier

spec:
  replicas: 1

  revisionHistoryLimit: 1

  selector:
    matchLabels:
      app: todo-backend

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  template:

    metadata:
      labels:
        app: todo-backend

    spec:

      imagePullSecrets:
      - name: dockerhub-secret

      containers:

      - name: todo-backend

        image: lekhanavemuri/todo-backend:8

        imagePullPolicy: Always

        ports:
        - containerPort: 3001

        envFrom:
        - secretRef:
            name: todo-secret

        startupProbe:
          tcpSocket:
            port: 3001
          failureThreshold: 30
          periodSeconds: 5

        readinessProbe:
          tcpSocket:
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 15

        resources:

          requests:
            cpu: "200m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"