apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
  namespace: todo-3tier-staging
spec:
  type: NodePort
  ports:
    - port: 6001
      targetPort: 6001
      nodePort: 30000
  selector:
    app: todo-backend
